name: Kernel Build, Telegram Notification, and Binary Upload

on: workflow_dispatch

jobs:
  Build_Notify_Upload_and_Clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Spinning up the environment
        run: bash <(curl -sL https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh)

      - name: Initialize Repo and Sync
        run: |
          repo init -u https://github.com/sajidshahriar72543/android_kernel_manifest -b android-msm-4.14
          repo sync --force-sync --no-clone-bundle --current-branch --no-tags -j$(nproc --all)

      - name: Notify Build Triggered and Get Commit Info
        id: notify_build
        run: |
          cd kernel/msm-4.14
          commit_sha=$(git rev-parse HEAD)
          commit_message=$(git log --format=%B -n 1)
          echo "::set-output name=commit_sha::$commit_sha"
          echo "::set-output name=commit_message::$commit_message"

      - name: Send Build Triggered Message with Commit Info
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.chat_id }}
          token: ${{ secrets.bot_token }}
          message: "Kernel build has been triggered.\n\nCommit: ${{ steps.notify_build.outputs.commit_sha }}.\n\nMessage: ${{ steps.notify_build.outputs.commit_message }}"

      - name: Build Kernel
        env:
          BUILD_KERNEL: 1
          BUILD_CONFIG: build.config
        run: build/build.sh

      - name: Send Prebuilt Images to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.chat_id }}
          token: ${{ secrets.bot_token }}
          message: "Kernel prebuilt images build completed."
          document: |
            out/main/dist/dtbo.img,
            out/main/dist/cust-atoll-ab.dtb,
            out/main/dist/Image.gz

      - name: Upload Kernel Binaries
        if: success()
        run: |
          git config --global user.email ${{ secrets.user_email }}
          git config --global user.name ${{ secrets.user_name }}
          cd out/main/dist
          git clone -b fourteen https://github.com/${{ secrets.user_name }}/device_xiaomi_miatoll-kernel krnl
          cp dtbo.img cust-atoll-ab.dtb Image.gz krnl/
          cd krnl
          git add .
          git commit -m "miatoll-kernel: update binaries"
          curl -Lo .git/hooks/commit-msg https://gerrit.pixelexperience.org/tools/hooks/commit-msg && chmod u+x .git/hooks/commit-msg
          git commit --amend -s --no-edit
          git push https://${{ secrets.user_name }}:${{ secrets.git_token }}@github.com/sajidshahriar72543/kernel_xiaomi_miatoll-kernel fourteen
          cd ../../../..
          
      - name: Clean Up
        if: success()
        run: |
          rm -rf out/
